apiVersion: v1
kind: Secret
metadata:
  name: bibsonomy-rest-api-db
type: Opaque
stringData:
  DATABASE_MAIN_URL: jdbc:mysql://YOUR_TEST_DB_HOST:3306/YOUR_MAIN_DB?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&mysqlEncoding=utf8&zeroDateTimeBehavior=convertToNull
  DATABASE_MAIN_USERNAME: REPLACE_ME
  DATABASE_MAIN_PASSWORD: REPLACE_ME
  DATABASE_MAIN_DRIVERCLASSNAME: com.mysql.jdbc.Driver
  DATABASE_RECOMMENDER_ITEM_URL: jdbc:mysql://YOUR_TEST_DB_HOST:3306/YOUR_ITEM_DB?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&mysqlEncoding=utf8&zeroDateTimeBehavior=convertToNull
  DATABASE_RECOMMENDER_ITEM_USERNAME: REPLACE_ME
  DATABASE_RECOMMENDER_ITEM_PASSWORD: REPLACE_ME
  DATABASE_RECOMMENDER_TAG_URL: jdbc:mysql://YOUR_TEST_DB_HOST:3306/YOUR_TAG_DB?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&mysqlEncoding=utf8&zeroDateTimeBehavior=convertToNull
  DATABASE_RECOMMENDER_TAG_USERNAME: REPLACE_ME
  DATABASE_RECOMMENDER_TAG_PASSWORD: REPLACE_ME
