apiVersion: v1
kind: Service
metadata:
  name: bibsonomy-rest-api-v2
spec:
  selector:
    app: bibsonomy-rest-api-v2
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32081
  type: NodePort
